bisok:
  model_name: 'klue/roberta-large'
  seed: 2021
  train_args:
    num_epochs: 10
    train_batch_size: 32
    max_seqlen: 128
    eval_batch_size: 8
    lr: 0.00001
    log_interval: 30
    weight_decay: 0.001
    save_dir: './models/bisok'
    optimizer: 'AdamW'
    scheduler_type: 'stepLr'
    steplr_gamma: 0.814 
    loss_fn: 'CEloss'
    label_smoothing_factor: 0.0
  val_args:
    fold_break: True
    n_splits: 20

other_com:
  model_name: 'klue/roberta-large' 
  seed: 2021
  train_args:
    num_epochs: 10
    train_batch_size: 32
    max_seqlen: 128
    eval_batch_size: 8
    lr: 0.00001
    log_interval: 30
    weight_decay: 0.001
    save_dir: './models/other_com'
    optimizer: 'AdamW'
    scheduler_type: 'stepLr'
    steplr_gamma: 0.814 
    loss_fn: 'CEloss'
    label_smoothing_factor: 0.0
  val_args:
    fold_break: True
    n_splits: 20

blind_famjob:
  model_name: 'klue/roberta-large'
  seed: 2021
  train_args:
    num_epochs: 10
    train_batch_size: 32
    max_seqlen: 128
    eval_batch_size: 8
    lr: 0.00001
    log_interval: 30
    weight_decay: 0.001
    save_dir: './models/blind_famjob'
    optimizer: 'AdamW'
    scheduler_type: 'stepLr'
    steplr_gamma: 0.814 
    loss_fn: 'CEloss'
    label_smoothing_factor: 0.0
  val_args:
    fold_break: True
    n_splits: 20

blind_gender:
  model_name: 'klue/roberta-large'
  seed: 2021
  train_args:
    num_epochs: 10
    train_batch_size: 32
    max_seqlen: 128
    eval_batch_size: 8
    lr: 0.00001
    log_interval: 30
    weight_decay: 0.001
    save_dir: './models/blind_gender'
    optimizer: 'AdamW'
    scheduler_type: 'stepLr'
    steplr_gamma: 0.814 
    loss_fn: 'CEloss'
    label_smoothing_factor: 0.0
  val_args:
    fold_break: True
    n_splits: 20

blind_local:
  model_name: 'klue/roberta-large'
  seed: 2021
  train_args:
    num_epochs: 10
    train_batch_size: 32
    max_seqlen: 128
    eval_batch_size: 8
    lr: 0.00001
    log_interval: 30
    weight_decay: 0.001
    save_dir: './models/blind_local'
    optimizer: 'AdamW'
    scheduler_type: 'stepLr'
    steplr_gamma: 0.814 
    loss_fn: 'CEloss'
    label_smoothing_factor: 0.0
  val_args:
    fold_break: True
    n_splits: 20

blind_schl:
  model_name: 'klue/roberta-large'
  seed: 2021
  train_args:
    num_epochs: 10
    train_batch_size: 32
    max_seqlen: 128
    eval_batch_size: 8
    lr: 0.00001
    log_interval: 30
    weight_decay: 0.001
    save_dir: './models/blind_schl'
    optimizer: 'AdamW'
    scheduler_type: 'stepLr'
    steplr_gamma: 0.814 
    loss_fn: 'CEloss'
    label_smoothing_factor: 0.0
  val_args:
    fold_break: True
    n_splits: 20

